### ISSUE TITLE
how can i get  the tier part

### ISSUE THREAD

**Issue by 717009629** [esbenbjerre/gsx-class#1]
![k6 k 0xmd6fr 3rr 4 e r](https://cloud.githubusercontent.com/assets/16289643/20589731/4f2e537c-b259-11e6-95c9-a3b0d0bf8d81.png)

when i creat Create Repair or Replace repair  ,need a  tier part ,but i do not know how to get it 
thank you

**Comment by esbenbjerre** [comment]
There is currently no API to retrieve the tier part for a repair, i do have a list of them but they only apply to the EMEA areas.
I got the list from GSX Web Services Support, so i suggest you send them an email at gsxws@apple.com :-)

**Comment by 717009629** [comment]
thank you
